### ISSUE TITLE
a problem during data pre-processing

### ISSUE THREAD

**Issue by Ritian-Li** [ms-dot-k/Visual-Audio-Memory#1]
https://github.com/ms-dot-k/Visual-Audio-Memory/blob/6509dcb96395eff5687df676eabbb6ee2705bb41/src/data/vid_aud_lrw.py#L119

Hi, when I run this code , it appear this problem during the data pre-processing. The dataset is LRW/lipread_mp4 .
![test](https://user-images.githubusercontent.com/60093100/142969313-303c11f1-b427-4c8f-b223-c795934ab421.png)

**Comment by ms-dot-k** [comment]
Hi, the message seems just a warning from PyTorch.

They say the function torchaudio.transforms.ComplexNorm() will be removed.

The command below
```shell
tf = torchaudio.transforms.ComplexNorm(2)
power_spec = tf(spec)
```

can be changed as
```shell
power_spec  = spec.abs().pow(2)
```
if you don't want to receive the warning.

Or if you don't need TimeStretch augmentation. 
Just extract the power spectrogram as,
```shell
torchaudio.transforms.Spectrogram(win_length=400, hop_length=160, power=2, normalized=True)
```

**Comment by Ritian-Li** [comment]
Do you mean to change it to this? 
but the spec is a spectrum object which doesn't have the attribute size. 
`        spec = torchaudio.transforms.Spectrogram(win_length=400, hop_length=160, power=2, normalized=True)
        ## Video ##
        video = video.permute(0, 3, 1, 2)  # T C H W
        num_v_frames = video.size(0)

        frames = self.build_tensor(video)
        num_a_frames = spec.size(2)  // AttributeError: 'Spectrogram' object has no attribute 'size'
        spec = nn.ConstantPad2d((0, num_v_frames * 4 - num_a_frames, 0, 0), 0.0)(spec)

        return spec, frames, target`

Besides, the illustration in the first reply means :
the size of specgram is [1, 201], if transpose it, the size will be changed as [201, 1].  
the size of self.fb is [201, 80], and they can't do torch.matmul operations.
So I changed this command to 
`torch.matmul(specgram, self.fb)`
But the dtypes of these variables are complex64 and float32..

Thank you for your reply!

**Comment by ms-dot-k** [comment]
I originally meant change the code
```shell
transform = nn.Sequential(
                torchaudio.transforms.Spectrogram(win_length=400, hop_length=160, power=None, normalized=True),
                torchaudio.transforms.TimeStretch(hop_length=160, fixed_rate=self.speed[ran]),
                torchaudio.transforms.ComplexNorm(2),
                torchaudio.transforms.MelScale(n_mels=80, sample_rate=16000),
                ...
)
mel=transform(aud)
```
to
```shell
transform = nn.Sequential(
                torchaudio.transforms.Spectrogram(win_length=400, hop_length=160, power=2, normalized=True),
                torchaudio.transforms.MelScale(n_mels=80, n_stft=201, sample_rate=16000),
                torchaudio.transforms.AmplitudeToDB(),
                ...
)
mel=transform(aud)
```
If you don't want to receive the warning. Please note the transform functions should be applied to audio.

Moreover, the spectrogram size should be '1, STFT_size, Time' not '1, 201'.
Please confirm the input audio size to the transform function is '1, audio_length'.
I recommend you to not change the source code of torchaudio!

**Comment by Ritian-Li** [comment]
so sorry to bother you so much !
After I changed the command, the size of spectrogram seems correct !
I printed some attributes of some varibles, now the questions is still the different dtypes of parameter specgram and self.fb.

`(Pdb) l 111,120
111                 transform = nn.Sequential(
112                     torchaudio.transforms.Spectrogram(win_length=400, hop_length=160, power=None, normalized=True), #100 fps (hop_length 10ms)
113                     # torchaudio.transforms.ComplexNorm(2),
114                     torchaudio.transforms.MelScale(n_mels=self.num_mel_bins, sample_rate=16000),
115                     torchaudio.transforms.AmplitudeToDB(),
116                     CMVN()
117                 )
118             import pdb; pdb.set_trace()
119  ->         spec = transform(aud)  # 1, 80, time*100 : C,F,T
120             pdb.set_trace()
(Pdb) file_path
'/media/zhuohe/DATA/LRW/lipread_mp4/SUNSHINE/train/SUNSHINE_00809.mp4'
(Pdb) p (aud.size(), video.size())
(torch.Size([1, 18560]), torch.Size([29, 256, 256, 3]))
(Pdb) c
> /home/zhuohe/anaconda3/envs/lp/lib/python3.6/site-packages/torchaudio/transforms.py(387)forward()
-> mel_specgram = torch.matmul(specgram.transpose(-1, -2), self.fb).transpose(-1, -2)
(Pdb) (specgram.size(), self.fb.size())
(torch.Size([1, 201, 117]), torch.Size([201, 80]))
(Pdb) (specgram.dtype, self.fb.dtype)
(torch.complex64, torch.float32)
(Pdb) l
382                 Tensor: Mel frequency spectrogram of size (..., ``n_mels``, time).
383             """
384  
385             # (..., time, freq) dot (freq, n_mels) -> (..., n_mels, time)
386             import pdb; pdb.set_trace()
387  ->         mel_specgram = torch.matmul(specgram.transpose(-1, -2), self.fb).transpose(-1, -2)
388  
389             return mel_specgram
390  
391  
392     class InverseMelScale(torch.nn.Module):
(Pdb) n
RuntimeError: expected scalar type ComplexFloat but found Float
> /home/zhuohe/anaconda3/envs/lp/lib/python3.6/site-packages/torchaudio/transforms.py(387)forward()
-> mel_specgram = torch.matmul(specgram.transpose(-1, -2), self.fb).transpose(-1, -2)`

**Comment by Ritian-Li** [comment]
so sorry to bother you so much !
After I changed the command, the size of spectrogram seems correct !
I printed some attributes of some varibles, now the questions is still the different dtypes of parameter specgram and self.fb.

![image](https://user-images.githubusercontent.com/60093100/143243603-055d798a-9a83-4279-b678-fd2dae6a5e1a.png)

**Comment by ms-dot-k** [comment]
After omitting the ComplexNorm function, please insert power=2 in the spectrogram function.
Therefore, the code 
```shell
transform = nn.Sequential(
torchaudio.transforms.Spectrogram(win_length=400, hop_length=160, power=None, normalized=True),
...
)
```
should become
```shell
transform = nn.Sequential(
torchaudio.transforms.Spectrogram(win_length=400, hop_length=160, power=2, normalized=True),
...
)
```

**Comment by Ritian-Li** [comment]
got it !
THANKS !!
