### ISSUE TITLE
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

### ISSUE THREAD

**Issue by srv-sh** [ms-dot-k/Visual-Audio-Memory#3]
while i am trying to test your model in aws i got an error. that is, 
**ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set** 
i saw some solution on google somewhere has been resolved  by providing **torch.distributed.launch --nproc_per_node=1**  this script before run the main.py . However I want to know is this script necessary for testing whereas i used CPU? 

can you tell me how can i fix this error and i want to use it in CPU so please give me the best solution to use it in CPU.

**Comment by srv-sh** [comment]
I used below script to test your model
`python -m torch.distributed.launch --nproc_per_node=1 main.py --lrw /home/ec2-user/SageMaker/lipread_mp4 --checkpoint ./data/MSTCN_Back_Ckpt.ckpt --batch_size 80 --backend MSTCN --mode test --radius 16 --n_slot 168 --test_aug True --distributed False --dataparallel False --gpu 0`
But  `torch.distributed.init_process_group(backend='nccl',init_method='env://')`   my compilation is stuck on this line.

**Comment by ms-dot-k** [comment]
For testing the model, you don't have to use the distributed data parallel. It is for training as mentioned in "Readme.md".
To test the model, run the following command:
```shell
# Testing example for LRW
python main.py \
--lrw 'enter_data_path' \
--checkpoint 'enter_the_checkpoint_path' \
--batch_size 80 \
--mode test --radius 16 --n_slot 88 \
--test_aug True --distributed False --dataparallel False \
--gpu 0
```

Moreover, the code basically uses GPU. So for CPU testing, you need to change some lines in "main.py".

**Comment by srv-sh** [comment]
Thank you for your replay. My issue is solved .

**Comment by joannahong** [comment]
Hello Sourav Saha, this is Joanna Hong, the coauthor of the paper of this repository.
Due to the privacy issue of the paper, we _**are not allowed to share the code of this paper**_. 
So we would like to politely ask you to delete **this "forked" repository**. 
We also would like to ask you to use the shared code **privately**.
We apologize your inconvenience. 
Thank you.
